POST http://localhost:5000/auth/register
Content-Type: application/json

{
	"email": "yogis_su@email.com",
	"password": "123456"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
	"email": "yogi_su@email.com",
	"password": "123456"
}

###
GET http://localhost:5000/auth/refresh_token

### 
DELETE http://localhost:5000/auth/logout

###
# pengujian token
GET http://localhost:5000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5IiwiZW1haWwiOiJ5b2dpX3N1QGVtYWlsLmNvbSIsInVzZXJuYW1lIjoieW9naV9zdSIsImlzX2FjdGl2ZSI6MCwiaWF0IjoxNjg1ODIwMjc5LCJleHAiOjE2ODU4MjAzMDl9.V74qE_yGgUouPSGXzjgUnZCLIFGen4TJv_Z8m304Qz4