POST http://localhost:5001/auth/register
Content-Type: application/json

{
	"email": "yogis_su@email.com",
	"password": "123456"
}

###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
	"email": "yogis_su@email.com",
	"password": "123456"
}

###
GET http://localhost:5001/auth/refresh_token

### 
DELETE http://localhost:5001/auth/logout

###
# pengujian token
GET http://localhost:5001/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5MyIsImVtYWlsIjoieW9naXNfc3VAZW1haWwuY29tIiwidXNlcm5hbWUiOiJ5b2dpc19zdSIsImlzX2FjdGl2ZSI6MCwiaWF0IjoxNjg3OTY5NTU4LCJleHAiOjE2ODgwNTk1NTh9.QLDevXJyi6t4NDFswAlQcFDfZ7Ubc30NYqCD2wPrSl4

###
#get all categories
GET http://localhost:5001/categories/

###
#get all sub categories
GET http://localhost:5001/subCategories/

###
#get sub categories by category code
GET http://localhost:5001/subCategories/tes01

###
#insert auction post
POST http://localhost:5001/auction/auctionPost/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5MyIsImVtYWlsIjoieW9naXNfc3VAZW1haWwuY29tIiwidXNlcm5hbWUiOiJ5b2dpc19zdSIsImlzX2FjdGl2ZSI6MCwiaWF0IjoxNjg4MDUzNTE4LCJleHAiOjE2ODgxMzk5MTh9.rg4u1WzHYfOWWsWRwR6_lzFd_WOkmQ7q5I29_lgLCm8

{
	"title": "uji coba post kedua agam", 
	"subCategoryCode": "sct002",
	"files": null,
	"condition": "Second",
	"initialPrice": 100000,
	"multiplePrice": 20000,
	"description": "tes keterangan atau description",
	"status": null,
	"startDate": null,
	"endDate": null,
	"tags": "lelang",
	"createdBy": null,
	"createdAt": ""
}

###
POST http://localhost:5001/auction/joinAuction/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5MyIsImVtYWlsIjoieW9naXNfc3VAZW1haWwuY29tIiwidXNlcm5hbWUiOiJ5b2dpc19zdSIsImlzX2FjdGl2ZSI6MCwiaWF0IjoxNjg4MDUzNTE4LCJleHAiOjE2ODgxMzk5MTh9.rg4u1WzHYfOWWsWRwR6_lzFd_WOkmQ7q5I29_lgLCm8

{
	"auctionPostCode": "ACP2302110001",
	"createdAt": null
}